import { SpriteTile } from '../models/cell.model';
import {
  dungeon_extension,
  tileA5_dungeon,
  tileB_dungeon,
} from './images';

export const rockWall: SpriteTile[] = [
  {
    id: 'FrontCenter',
    spriteGridPosX: 1,
    spriteGridPosY: 3,
    tileHeight: 3,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    addon: "caveWallAddon",
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: false,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    },
  },
  {
    id: 'FrontLeft',
    spriteGridPosX: 0,
    spriteGridPosY: 3,
    tileHeight: 3,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: false,
      bottomLeftNeighbor: false,
      leftNeighbor: null,
      topLeftNeighbor: null,
    },
  },
  {
    id: 'FrontRight',
    spriteGridPosX: 2,
    spriteGridPosY: 7,
    tileHeight: 3,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: null,
      rightNeighbor: false,
      bottomRightNeighbor: false,
      bottomNeighbor: false,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    },
  },
  {
    id: 'MidLeft',
    spriteGridPosX: 0,
    spriteGridPosY: 2,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    visionBlocking: false,
    obstacle: false,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: true,
      bottomLeftNeighbor: null,
      leftNeighbor: false,
      topLeftNeighbor: null,
    },
  },
    {
      id: 'MidCenter',
      spriteGridPosX: 3,
      spriteGridPosY: 12,
      tileHeight: 1,
      tileWidth: 1,
      tileOffsetX: 0,
      tileOffsetY: -64,
      visionBlocking: false,
      obstacle: false,
      default: true,
      obstacleObstructionX: 1,
      obstacleObstructionY: 1,
      drawWhen: {
        topNeighbor: true,
        topRightNeighbor: true,
        rightNeighbor: true,
        bottomRightNeighbor: true,
        bottomNeighbor: true,
        bottomLeftNeighbor: true,
        leftNeighbor: true,
        topLeftNeighbor: true,
      },
    },
    {
      id: 'MidRight',
      spriteGridPosX: 0,
      spriteGridPosY: 1,
      tileHeight: 1,
      tileWidth: 1,
      tileOffsetX: 0,
      tileOffsetY: -64,
      visionBlocking: false,
      obstacle: false,
      obstacleObstructionX: 1,
      obstacleObstructionY: 1,
      drawWhen: {
        topNeighbor: true,
        topRightNeighbor: null,
        rightNeighbor: false,
        bottomRightNeighbor: null,
        bottomNeighbor: true,
        bottomLeftNeighbor: null,
        leftNeighbor: true,
        topLeftNeighbor: null,
      },
    },
    {
      id: 'TopLeft',
      spriteGridPosX: 0,
      spriteGridPosY: 0,
      tileHeight: 1,
      tileWidth: 1,
      tileOffsetX: 0,
      tileOffsetY: -64,
      visionBlocking: false,
      obstacle: false,
      obstacleObstructionX: 1,
      obstacleObstructionY: 1,
      drawWhen: {
        topNeighbor: false,
        topRightNeighbor: null,
        rightNeighbor: true,
        bottomRightNeighbor: true,
        bottomNeighbor: true,
        bottomLeftNeighbor: null,
        leftNeighbor: false,
        topLeftNeighbor: false,
      },
    },
    {
      id: 'TopCenter',
      spriteGridPosX: 1,
      spriteGridPosY: 0,
      tileHeight: 1,
      tileWidth: 1,
      tileOffsetX: 0,
      tileOffsetY: -64,
      visionBlocking: false,
      obstacle: false,
      obstacleObstructionX: 1,
      obstacleObstructionY: 1,
      drawWhen: {
        topNeighbor: false,
        topRightNeighbor: null,
        rightNeighbor: true,
        bottomRightNeighbor: null,
        bottomNeighbor: true,
        bottomLeftNeighbor: null,
        leftNeighbor: true,
        topLeftNeighbor: null,
      },
    },
    {
      id: 'TopRight',
      spriteGridPosX: 2,
      spriteGridPosY: 0,
      tileHeight: 1,
      tileWidth: 1,
      tileOffsetX: 0,
      tileOffsetY: -64,
      visionBlocking: false,
      obstacle: false,
      obstacleObstructionX: 1,
      obstacleObstructionY: 1,
      drawWhen: {
        topNeighbor: false,
        topRightNeighbor: null,
        rightNeighbor: false,
        bottomRightNeighbor: null,
        bottomNeighbor: true,
        bottomLeftNeighbor: null,
        leftNeighbor: true,
        topLeftNeighbor: null,
      },
    },
  ];









  // {
  //   id: 'FrontLeft',
  //   spriteSheet: dungeon_extension,
  //   spriteGridPosX: 1,
  //   spriteGridPosY: 0,
  //   tileHeight: 1,
  //   tileWidth: 1,
  //   tileOffsetX: 0,
  //   tileOffsetY: -64,
  //   multiplier: 32,
  //   visionBlocking: false,
  //   obstacle: true,
  //   obstacleObstructionX: 1,
  //   obstacleObstructionY: 1,
  //   drawWhen: {
  //     topNeighbor: true,
  //     topRightNeighbor: null,
  //     rightNeighbor: false,
  //     bottomRightNeighbor: null,
  //     bottomNeighbor: true,
  //     bottomLeftNeighbor: true,
  //     leftNeighbor: true,
  //     topLeftNeighbor: true,
  //   },
  // },
  // {
  //   id: 'cliffRightSingle',
  //   spriteSheet: dungeon_extension,
  //   spriteGridPosX: 0,
  //   spriteGridPosY: 0,
  //   tileHeight: 1,
  //   tileWidth: 1,
  //   tileOffsetX: 0,
  //   tileOffsetY: -64,
  //   multiplier: 32,
  //   visionBlocking: false,
  //   obstacle: true,
  //   obstacleObstructionX: 1,
  //   obstacleObstructionY: 1,
  //   drawWhen: {
  //     topNeighbor: true,
  //     topRightNeighbor: true,
  //     rightNeighbor: true,
  //     bottomRightNeighbor: true,
  //     bottomNeighbor: true,
  //     bottomLeftNeighbor: null,
  //     leftNeighbor: false,
  //     topLeftNeighbor: null,
  //   },
  // },
  
  
  // },
  // {
  //   id: 'cliffLeftCorner',
  //   spriteSheet: tileA5_dungeon,
  //   spriteGridPosX: 0,
  //   spriteGridPosY: 7,
  //   tileHeight: 3,
  //   tileWidth: 1,
  //   tileOffsetX: 0,
  //   tileOffsetY: -64,
  //   multiplier: 32,
  //   visionBlocking: false,
  //   obstacle: true,
  //   obstacleObstructionX: 1,
  //   obstacleObstructionY: 1,
  //   drawWhen: {
  //     topNeighbor: null,
  //     topRightNeighbor: null,
  //     rightNeighbor: true,
  //     bottomRightNeighbor: null,
  //     bottomNeighbor: false,
  //     bottomLeftNeighbor: false,
  //     leftNeighbor: null,
  //     topLeftNeighbor: null,
  //   },
  // },
  // {
  //   id: 'BlackCenter',
  //   spriteSheet: tileA5_dungeon,
  //   default: true,
  //   spriteGridPosX: 1,
  //   spriteGridPosY: 6,
  //   tileHeight: 1,
  //   tileWidth: 1,
  //   tileOffsetX: 0,
  //   tileOffsetY: -64,
  //   multiplier: 32,
  //   visionBlocking: false,
  //   obstacle: true,
  //   obstacleObstructionX: 1,
  //   obstacleObstructionY: 1,
  //   drawWhen: {
  //     topNeighbor: true,
  //     topRightNeighbor: true,
  //     rightNeighbor: true,
  //     bottomRightNeighbor: true,
  //     bottomNeighbor: true,
  //     bottomLeftNeighbor: true,
  //     leftNeighbor: true,
  //     topLeftNeighbor: true,
  //   },
  // },

  // {
  //   id: 'cliffLeftTopCorner',
  //   spriteSheet: tileA5_dungeon,
  //   spriteGridPosX: 7,
  //   spriteGridPosY: 6,
  //   tileHeight: 1,
  //   tileWidth: 1,
  //   tileOffsetX: 0,
  //   tileOffsetY: -64,
  //   multiplier: 32,
  //   visionBlocking: false,
  //   obstacle: true,
  //   obstacleObstructionX: 1,
  //   obstacleObstructionY: 1,
  //   drawWhen: {
  //     topNeighbor: true,
  //     topRightNeighbor: true,
  //     rightNeighbor: true,
  //     bottomRightNeighbor: false,
  //     bottomNeighbor: true,
  //     bottomLeftNeighbor: true,
  //     leftNeighbor: true,
  //     topLeftNeighbor: true,
  //   },
  // },
  // {
  //   id: 'cliffRightTopCorner',
  //   spriteSheet: tileA5_dungeon,
  //   spriteGridPosX: 6,
  //   spriteGridPosY: 6,
  //   tileHeight: 1,
  //   tileWidth: 1,
  //   tileOffsetX: 0,
  //   tileOffsetY: -64,
  //   multiplier: 32,
  //   visionBlocking: false,
  //   obstacle: true,
  //   obstacleObstructionX: 1,
  //   obstacleObstructionY: 1,
  //   drawWhen: {
  //     topNeighbor: true,
  //     topRightNeighbor: true,
  //     rightNeighbor: true,
  //     bottomRightNeighbor: true,
  //     bottomNeighbor: true,
  //     bottomLeftNeighbor: false,
  //     leftNeighbor: true,
  //     topLeftNeighbor: true,
  //   },
  // },
  // {
  //   id: 'cliffLeftBottomCorner',
  //   spriteSheet: tileA5_dungeon,
  //   spriteGridPosX: 7,
  //   spriteGridPosY: 5,
  //   tileHeight: 1,
  //   tileWidth: 1,
  //   tileOffsetX: 0,
  //   tileOffsetY: -64,
  //   multiplier: 32,
  //   visionBlocking: false,
  //   obstacle: true,
  //   obstacleObstructionX: 1,
  //   obstacleObstructionY: 1,
  //   drawWhen: {
  //     topNeighbor: true,
  //     topRightNeighbor: false,
  //     rightNeighbor: true,
  //     bottomRightNeighbor: true,
  //     bottomNeighbor: true,
  //     bottomLeftNeighbor: true,
  //     leftNeighbor: true,
  //     topLeftNeighbor: true,
  //   },
  // },
  // {
  //   id: 'cliffRightBottomCorner',
  //   spriteSheet: tileA5_dungeon,
  //   spriteGridPosX: 6,
  //   spriteGridPosY: 5,
  //   tileHeight: 1,
  //   tileWidth: 1,
  //   tileOffsetX: 0,
  //   tileOffsetY: -64,
  //   multiplier: 32,
  //   visionBlocking: false,
  //   obstacle: true,
  //   obstacleObstructionX: 1,
  //   obstacleObstructionY: 1,
  //   drawWhen: {
  //     topNeighbor: true,
  //     topRightNeighbor: true,
  //     rightNeighbor: true,
  //     bottomRightNeighbor: true,
  //     bottomNeighbor: true,
  //     bottomLeftNeighbor: true,
  //     leftNeighbor: true,
  //     topLeftNeighbor: false,
  //   },
  // },
  // {
  //   id: 'cliffTopLeftEdge',
  //   spriteSheet: tileB_dungeon,
  //   spriteGridPosX: 5,
  //   spriteGridPosY: 0,
  //   tileHeight: 1,
  //   tileWidth: 1,
  //   tileOffsetX: 0,
  //   tileOffsetY: -64,
  //   multiplier: 32,
  //   visionBlocking: false,
  //   obstacle: true,
  //   obstacleObstructionX: 1,
  //   obstacleObstructionY: 1,
  //   drawWhen: {
  //     topNeighbor: false,
  //     topRightNeighbor: null,
  //     rightNeighbor: true,
  //     bottomRightNeighbor: true,
  //     bottomNeighbor: true,
  //     bottomLeftNeighbor: null,
  //     leftNeighbor: false,
  //     topLeftNeighbor: false,
  //   },
  // },
  // {
  //   id: 'cliffTopCenterEdge',
  //   spriteSheet: tileB_dungeon,
  //   spriteGridPosX: 6,
  //   spriteGridPosY: 0,
  //   tileHeight: 1,
  //   tileWidth: 1,
  //   tileOffsetX: 0,
  //   tileOffsetY: -64,
  //   multiplier: 32,
  //   visionBlocking: false,
  //   obstacle: true,
  //   obstacleObstructionX: 1,
  //   obstacleObstructionY: 1,
  //   drawWhen: {
  //     topNeighbor: false,
  //     topRightNeighbor: null,
  //     rightNeighbor: true,
  //     bottomRightNeighbor: null,
  //     bottomNeighbor: true,
  //     bottomLeftNeighbor: null,
  //     leftNeighbor: true,
  //     topLeftNeighbor: null,
  //   },
  // },
  // {
  //   id: 'cliffTopRightEdge',
  //   spriteSheet: tileB_dungeon,
  //   spriteGridPosX: 7,
  //   spriteGridPosY: 0,
  //   tileHeight: 1,
  //   tileWidth: 1,
  //   tileOffsetX: 0,
  //   tileOffsetY: -64,
  //   multiplier: 32,
  //   visionBlocking: false,
  //   obstacle: true,
  //   obstacleObstructionX: 1,
  //   obstacleObstructionY: 1,
  //   drawWhen: {
  //     topNeighbor: false,
  //     topRightNeighbor: false,
  //     rightNeighbor: false,
  //     bottomRightNeighbor: null,
  //     bottomNeighbor: true,
  //     bottomLeftNeighbor: null,
  //     leftNeighbor: true,
  //     topLeftNeighbor: null,
  //   },
  // },

