import { SpriteTile } from "../models/cell.model";

export const RockWall: SpriteTile[] = [
    {
      id: 'FrontCenter',
      spriteGridPosX: 1,
      spriteGridPosY: 3,
      tileHeight: 3,
      tileWidth: 1,
      tileOffsetX: 0,
      tileOffsetY: -64,
      visionBlocking: false,
      obstacle: true,
      obstacleObstructionX: 1,
      obstacleObstructionY: 1,
      addon: "caveWallAddon",
      drawWhen: {
        topNeighbor: true,
        topRightNeighbor: null,
        rightNeighbor: true,
        bottomRightNeighbor: false,
        bottomNeighbor: false,
        bottomLeftNeighbor: false,
        leftNeighbor: true,
        topLeftNeighbor: null,
      },
    },
    {
      id: 'FrontLeft',
      spriteGridPosX: 0,
      spriteGridPosY: 3,
      tileHeight: 3,
      tileWidth: 1,
      tileOffsetX: 0,
      tileOffsetY: -64,
      visionBlocking: false,
      obstacle: true,
      obstacleObstructionX: 1,
      obstacleObstructionY: 1,
      drawWhen: {
        topNeighbor: true,
        topRightNeighbor: null,
        rightNeighbor: true,
        bottomRightNeighbor: null,
        bottomNeighbor: false,
        bottomLeftNeighbor: false,
        leftNeighbor: false,
        topLeftNeighbor: null,
      },
    },
    {
      id: 'FrontRight',
      spriteGridPosX: 2,
      spriteGridPosY: 3,
      tileHeight: 3,
      tileWidth: 1,
      tileOffsetX: 0,
      tileOffsetY: -64,
      visionBlocking: false,
      obstacle: true,
      obstacleObstructionX: 1,
      obstacleObstructionY: 1,
      drawWhen: {
        topNeighbor: true,
        topRightNeighbor: false,
        rightNeighbor: false,
        bottomRightNeighbor: false,
        bottomNeighbor: false,
        bottomLeftNeighbor: null,
        leftNeighbor: true,
        topLeftNeighbor: null,
      },
    },
    {
      id: 'MidLeft',
      spriteGridPosX: 0,
      spriteGridPosY: 2,
      tileHeight: 1,
      tileWidth: 1,
      tileOffsetX: 0,
      tileOffsetY: -64,
      visionBlocking: false,
      obstacle: false,
      obstacleObstructionX: 1,
      obstacleObstructionY: 1,
      drawWhen: {
        topNeighbor: true,
        topRightNeighbor: null,
        rightNeighbor: true,
        bottomRightNeighbor: null,
        bottomNeighbor: true,
        bottomLeftNeighbor: null,
        leftNeighbor: false,
        topLeftNeighbor: null,
      },
    },
      {
        id: 'MidCenter',
        spriteGridPosX: 3,
        spriteGridPosY: 12,
        tileHeight: 1,
        tileWidth: 1,
        tileOffsetX: 0,
        tileOffsetY: -64,
        visionBlocking: false,
        obstacle: false,
        default: true,
        obstacleObstructionX: 1,
        obstacleObstructionY: 1,
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: true,
          rightNeighbor: true,
          bottomRightNeighbor: true,
          bottomNeighbor: true,
          bottomLeftNeighbor: true,
          leftNeighbor: true,
          topLeftNeighbor: true,
        },
      },
      {
        id: 'MidRight',
        spriteGridPosX: 0,
        spriteGridPosY: 1,
        tileHeight: 1,
        tileWidth: 1,
        tileOffsetX: 0,
        tileOffsetY: -64,
        visionBlocking: false,
        obstacle: false,
        obstacleObstructionX: 1,
        obstacleObstructionY: 1,
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: null,
          rightNeighbor: false,
          bottomRightNeighbor: null,
          bottomNeighbor: true,
          bottomLeftNeighbor: null,
          leftNeighbor: true,
          topLeftNeighbor: null,
        },
      },
      {
        id: 'TopLeft',
        spriteGridPosX: 0,
        spriteGridPosY: 0,
        tileHeight: 1,
        tileWidth: 1,
        tileOffsetX: 0,
        tileOffsetY: -64,
        visionBlocking: false,
        obstacle: false,
        obstacleObstructionX: 1,
        obstacleObstructionY: 1,
        drawWhen: {
          topNeighbor: false,
          topRightNeighbor: null,
          rightNeighbor: true,
          bottomRightNeighbor: true,
          bottomNeighbor: true,
          bottomLeftNeighbor: null,
          leftNeighbor: false,
          topLeftNeighbor: false,
        },
      },
      {
        id: 'TopCenter',
        spriteGridPosX: 1,
        spriteGridPosY: 0,
        tileHeight: 1,
        tileWidth: 1,
        tileOffsetX: 0,
        tileOffsetY: -64,
        visionBlocking: false,
        obstacle: false,
        obstacleObstructionX: 1,
        obstacleObstructionY: 1,
        drawWhen: {
          topNeighbor: false,
          topRightNeighbor: null,
          rightNeighbor: true,
          bottomRightNeighbor: null,
          bottomNeighbor: true,
          bottomLeftNeighbor: null,
          leftNeighbor: true,
          topLeftNeighbor: null,
        },
      },
      {
        id: 'TopRight',
        spriteGridPosX: 2,
        spriteGridPosY: 0,
        tileHeight: 1,
        tileWidth: 1,
        tileOffsetX: 0,
        tileOffsetY: -64,
        visionBlocking: false,
        obstacle: false,
        obstacleObstructionX: 1,
        obstacleObstructionY: 1,
        drawWhen: {
          topNeighbor: false,
          topRightNeighbor: null,
          rightNeighbor: false,
          bottomRightNeighbor: null,
          bottomNeighbor: true,
          bottomLeftNeighbor: null,
          leftNeighbor: true,
          topLeftNeighbor: null,
        },
      },

      {
        id: 'FontLeftAttach',
        spriteGridPosX: 3,
        spriteGridPosY: 0,
        tileHeight: 3,
        tileWidth: 1,
        tileOffsetX: 0,
        tileOffsetY: -64,
        visionBlocking: false,
        obstacle: true,
        obstacleObstructionX: 1,
        obstacleObstructionY: 1,
        addon: "caveWallAddon",
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: null,
          rightNeighbor: true,
          bottomRightNeighbor: null,
          bottomNeighbor: false,
          bottomLeftNeighbor: true,
          leftNeighbor: true,
          topLeftNeighbor: null,
        },
      },
      {
        id: 'FontRightAttach',
        spriteGridPosX: 4,
        spriteGridPosY: 0,
        tileHeight: 3,
        tileWidth: 1,
        tileOffsetX: 0,
        tileOffsetY: -64,
        visionBlocking: false,
        obstacle: true,
        obstacleObstructionX: 1,
        obstacleObstructionY: 1,
        addon: "caveWallAddon",
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: null,
          rightNeighbor: true,
          bottomRightNeighbor: true,
          bottomNeighbor: false,
          bottomLeftNeighbor: null,
          leftNeighbor: true,
          topLeftNeighbor: null,
        },
      },
      {
        id: 'FontRightAdjacentAttach',
        spriteGridPosX: 4,
        spriteGridPosY: 3,
        tileHeight: 3,
        tileWidth: 1,
        tileOffsetX: 0,
        tileOffsetY: -64,
        visionBlocking: false,
        obstacle: true,
        obstacleObstructionX: 1,
        obstacleObstructionY: 1,
        addon: "caveWallAddon",
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: true,
          rightNeighbor: false,
          bottomRightNeighbor: null,
          bottomNeighbor: false,
          bottomLeftNeighbor: null,
          leftNeighbor: true,
          topLeftNeighbor: null,
        },
      },
      {
        id: 'bottomLeftFillerSquare',
        spriteGridPosX: 1,
        spriteGridPosY: 2,
        tileHeight: 1,
        tileWidth: 1,
        tileOffsetX: 0,
        tileOffsetY: -64,
        visionBlocking: false,
        obstacle: true,
        obstacleObstructionX: 1,
        obstacleObstructionY: 1,
        addon: "caveWallAddon",
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: true,
          rightNeighbor: true,
          bottomRightNeighbor: true,
          bottomNeighbor: true,
          bottomLeftNeighbor: false,
          leftNeighbor: true,
          topLeftNeighbor: true,
        },
      },
      {
        id: 'bottomRightFillerSquare',
        spriteGridPosX: 2,
        spriteGridPosY: 2,
        tileHeight: 1,
        tileWidth: 1,
        tileOffsetX: 0,
        tileOffsetY: -64,
        visionBlocking: false,
        obstacle: true,
        obstacleObstructionX: 1,
        obstacleObstructionY: 1,
        addon: "caveWallAddon",
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: true,
          rightNeighbor: true,
          bottomRightNeighbor: false,
          bottomNeighbor: true,
          bottomLeftNeighbor: true,
          leftNeighbor: true,
          topLeftNeighbor: true,
        },
      },
      {
        id: 'TopLeftFillerSquare',
        spriteGridPosX: 1,
        spriteGridPosY: 1,
        tileHeight: 1,
        tileWidth: 1,
        tileOffsetX: 0,
        tileOffsetY: -64,
        visionBlocking: false,
        obstacle: true,
        obstacleObstructionX: 1,
        obstacleObstructionY: 1,
        addon: "caveWallAddon",
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: true,
          rightNeighbor: true,
          bottomRightNeighbor: true,
          bottomNeighbor: true,
          bottomLeftNeighbor: true,
          leftNeighbor: true,
          topLeftNeighbor: false,
        },
      },
      {
        id: 'TopRightFillerSquare',
        spriteGridPosX: 2,
        spriteGridPosY: 1,
        tileHeight: 1,
        tileWidth: 1,
        tileOffsetX: 0,
        tileOffsetY: -64,
        visionBlocking: false,
        obstacle: true,
        obstacleObstructionX: 1,
        obstacleObstructionY: 1,
        addon: "caveWallAddon",
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: false,
          rightNeighbor: true,
          bottomRightNeighbor: true,
          bottomNeighbor: true,
          bottomLeftNeighbor: true,
          leftNeighbor: true,
          topLeftNeighbor: true,
        },
      },
    ];