import { Injectable } from "@angular/core";
import { GSM } from "../app.service.manager";
import { getBackgroundCollection, getObjectCollection } from "../game-assets/tile-assets.db";
import { DefaultMapSettings, SpriteBackgroundTile, SpriteTile } from "../models/cell.model";
import { GameSettings } from "../models/game-settings";
import { PageTransitionMarker } from "../models/marker-icon.model";
import { RandomMapGenerator } from "../utils/random-map-generator";

@Injectable()
export class EditorService {
  public selectedAsset: SpriteTile
  public selectedGrowableAsset = ""
  public layerID = 1 

  public findBackgroundCollection(category: string): SpriteBackgroundTile[] {
    return getBackgroundCollection(category)
  }

  public findObjectCollection(category: string): SpriteTile[] {
    return getObjectCollection(category)
  }
 
  public findBackgroundAsset(category: string, tileId: string): SpriteBackgroundTile {
    return getBackgroundCollection(category).find((tile: SpriteBackgroundTile) => tile.id === tileId)
  } 
 
  public findObjectAsset(category: string, tileId: string): SpriteTile {
    return getObjectCollection(category).find((tile: SpriteBackgroundTile) => tile.id === tileId)
  } 

  public generateRandomCoreMap(): void {
    const mapDetails: DefaultMapSettings = {
      autoGeneratedMap: true,
      backgroundTypeId: "greenGrass",
      terrainTypeId: "Trees-GrassBase",
      inverted: false,
      pathTypeId: "DrawableDirtRoad",
    }

    RandomMapGenerator.generateMap(96, 96, mapDetails)
    GSM.Canvas.setupCanvases()
    GSM.FogOfWar.setup()

    // CLEANUP - Needs to be moved into somewhere that re-draws
    const centerCell = GSM.Map.activeMap.getGridCellByCoordinate(Math.floor(GSM.Canvas.canvasSizeX / 2), Math.floor(GSM.Canvas.canvasSizeY / 2))
    GSM.Canvas.centerPointX = centerCell.posX * GameSettings.scale
    GSM.Canvas.centerPointY = centerCell.posY * GameSettings.scale

    GSM.Draw.blackOutFogPainter.paint()
  }

  public generateRandomAttachmentMap(markerIcon: PageTransitionMarker): void {
    // allow for override
    const mapDetails: DefaultMapSettings = {
      autoGeneratedMap: true,
      backgroundTypeId: "greenGrass",
      terrainTypeId: "DrawableTrees",
      inverted: false,
      pathTypeId: "DrawableDirtRoad"
    }
   
    RandomMapGenerator.generateAttachmentMap(GSM.Map.activeMap, mapDetails, markerIcon)
    GSM.Canvas.setupCanvases()
  }

  public togglePlayMode(): void {
    if (!GSM.Map.activeMap) { return }

    GSM.Canvas.editMode = !GSM.Canvas.editMode
    setTimeout(() => {
      if (!GSM.Canvas.editMode) {
        GSM.Map.activeMap.largeImage.createLargeImage(GSM.Map.activeMap.width * 32, GSM.Map.activeMap.height * 32, GSM.Map.activeMap)
      } else {
        if (GSM.Map.activeMap) {
          GSM.Map.activeMap.largeImage.background = undefined
        }
      }
    })
  }

} 