import { SpriteTile } from "../../models/cell.model";
import { tf_winter_tileB } from "./images";

export const camping: SpriteTile[] = [
  {
    id: "tent",
    spriteSheet: tf_winter_tileB,
    spriteGridPosX: 8,
    spriteGridPosY: 7,
    tileHeight: 4,
    tileWidth: 3,
    tileOffsetX: 0,
    tileOffsetY: -96,
    multiplier: 32,
    visionBlocking: true,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  },
  {
    id: "doorCloses",
    spriteSheet: tf_winter_tileB,
    spriteGridPosX: 14,
    spriteGridPosY: 9,
    tileHeight: 2,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -32,
    multiplier: 32,
    visionBlocking: true,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  },
  {
    id: "foodHanger",
    spriteSheet: tf_winter_tileB,
    spriteGridPosX: 8,
    spriteGridPosY: 11,
    tileHeight: 2,
    tileWidth: 3,
    tileOffsetX: 0,
    tileOffsetY: -32,
    multiplier: 32,
    visionBlocking: true,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  },
  {
    id: "foodHangerPot1",
    spriteSheet: tf_winter_tileB,
    spriteGridPosX: 11,
    spriteGridPosY: 11,
    tileHeight: 2,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -32,
    multiplier: 32,
    visionBlocking: true,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  },
  {
    id: "foodHangerPot2",
    spriteSheet: tf_winter_tileB,
    spriteGridPosX: 12,
    spriteGridPosY: 11,
    tileHeight: 2,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -32,
    multiplier: 32,
    visionBlocking: true,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  },
  {
    id: "foodHangerPot3",
    spriteSheet: tf_winter_tileB,
    spriteGridPosX: 15,
    spriteGridPosY: 11,
    tileHeight: 2,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -32,
    multiplier: 32,
    visionBlocking: true,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  },
  {
    id: "foodHangerMeet1",
    spriteSheet: tf_winter_tileB,
    spriteGridPosX: 13,
    spriteGridPosY: 11,
    tileHeight: 2,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -32,
    multiplier: 32,
    visionBlocking: true,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  },
  {
    id: "foodHangerMeet2",
    spriteSheet: tf_winter_tileB,
    spriteGridPosX: 14,
    spriteGridPosY: 11,
    tileHeight: 2,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -32,
    multiplier: 32,
    visionBlocking: true,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  },
  {
    id: "smallFirePit",
    spriteSheet: tf_winter_tileB,
    spriteGridPosX: 8,
    spriteGridPosY: 13,
    tileHeight: 2,
    tileWidth: 3,
    tileOffsetX: -16,
    tileOffsetY: -16,
    multiplier: 32,
    visionBlocking: true,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  },
  {
    id: "LargeFirePit",
    spriteSheet: tf_winter_tileB,
    spriteGridPosX: 11,
    spriteGridPosY: 13,
    tileHeight: 3,
    tileWidth: 3,
    tileOffsetX: 0,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: true,
    obstacle: true,
    obstacleObstructionX: 3,
    obstacleObstructionY: 3,
  },
]