import { GridService } from "../../grid/grid.service";
import { GrowablePanelPosition, SpriteTile } from "../../models/cell.model";
import { tileA5_outside } from "./images";






export const cliffs: SpriteTile[] = [
  {
    id: "cliffTopLeft",
    position: GrowablePanelPosition.topLeftPanel,
    spriteSheet: tileA5_outside,
    spriteGridPosX: 0,
    spriteGridPosY: 11,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: 0,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  },
  {
    id: "cliffTopCenter",
    position: GrowablePanelPosition.topCenterPanel,
    spriteSheet: tileA5_outside,
    spriteGridPosX: 1,
    spriteGridPosY: 11,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: 0,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  },
  {
    id: "cliffTopRight",
    position: GrowablePanelPosition.topRightPanel,
    spriteSheet: tileA5_outside,
    spriteGridPosX: 2,
    spriteGridPosY: 11,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: 0,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  },
  {
    id: "cliffGrowableLeft",
    position: GrowablePanelPosition.growableLeftPanel,
    spriteSheet: tileA5_outside,
    spriteGridPosX: 0,
    spriteGridPosY: 12,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: 0,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  },
  {
    id: "cliffGrowableCenter",
    position: GrowablePanelPosition.growableCenterPanel,
    spriteSheet: tileA5_outside,
    spriteGridPosX: 1,
    spriteGridPosY: 12,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: 0,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  },
  {
    id: "cliffGrowableRight",
    position: GrowablePanelPosition.growableRightPanel,
    spriteSheet: tileA5_outside,
    spriteGridPosX: 2,
    spriteGridPosY: 12,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: 0,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  },
  {
    id: "cliffBottomLeft",
    position: GrowablePanelPosition.bottomLeftPanel,
    spriteSheet: tileA5_outside,
    spriteGridPosX: 0,
    spriteGridPosY: 13,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: 0,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  },
  {
    id: "cliffBottomCenter",
    position: GrowablePanelPosition.bottomCenterPanel,
    spriteSheet: tileA5_outside,
    spriteGridPosX: 1,
    spriteGridPosY: 13,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: 0,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  },
  {
    id: "cliffBottomRight",
    position: GrowablePanelPosition.bottomRightPanel,
    spriteSheet: tileA5_outside,
    spriteGridPosX: 2,
    spriteGridPosY: 13,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: 0,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  },
]

export const GrowableCliffs = {
  id: "DrawableDirtCliff",
  topLeftPanel: cliffs.find(panel => panel.position === GrowablePanelPosition.topLeftPanel),
  topCenterPanel: cliffs.find(panel => panel.position === GrowablePanelPosition.topCenterPanel),
  topRightPanel: cliffs.find(panel => panel.position === GrowablePanelPosition.topRightPanel),
  bottomLeftPanel: cliffs.find(panel => panel.position === GrowablePanelPosition.bottomLeftPanel),
  bottomCenterPanel: cliffs.find(panel => panel.position === GrowablePanelPosition.bottomCenterPanel),
  bottomRightPanel: cliffs.find(panel => panel.position === GrowablePanelPosition.bottomRightPanel),
  growableLeftPanel: cliffs.find(panel => panel.position === GrowablePanelPosition.growableLeftPanel),
  growableCenterPanel: cliffs.find(panel => panel.position === GrowablePanelPosition.growableCenterPanel),
  growableRightPanel: cliffs.find(panel => panel.position === GrowablePanelPosition.growableRightPanel),
}






// export const cliffs: SpriteTile[] = [
//   {
//     id: "leftCliffSide",
//     spriteSheet: tileA5_outside,
//     spriteGridPosX: 0,
//     spriteGridPosY: 12,
//     tileHeight: 2,
//     tileWidth: 1,
//     tileOffsetX: 0,
//     tileOffsetY: -32,
//     multiplier: 32,
//     visionBlocking: false,
//     obstacle: true,
//     obstacleObstructionX: 1,
//     obstacleObstructionY: 3,
//     centerTileName: "centerCliffFace",
//     topEndTileName: {
//       name: "cliffTopLeft",
//       offset: -96
//     },
//     attachments: [{
//       tileName: "cliffLeftEdge",
//       neighborPosition: 0,
//       xOffset: 0,
//       yOffset: -64
//     }]
//   },
//   {
//     id: "centerCliffFace",
//     spriteSheet: tileA5_outside,
//     spriteGridPosX: 1,
//     spriteGridPosY: 12,
//     tileHeight: 2,
//     tileWidth: 1,
//     tileOffsetX: 0,
//     tileOffsetY: -32,
//     multiplier: 32,
//     visionBlocking: false,
//     obstacle: true,
//     obstacleObstructionX: 1,
//     obstacleObstructionY: 3,
//     leftEndTileName: "leftCliffSide",
//     rightEndTileName: "rightTreeClump",
//     topEndTileName: {
//       name: "cliffTopCenter",
//       offset: -96
//     },
//     attachments: [{
//       tileName: "cliffCenter",
//       neighborPosition: 0,
//       xOffset: 0,
//       yOffset: -64
//     }]
//   },
//   {
//     id: "rightTreeClump",
//     spriteSheet: tileA5_outside,
//     spriteGridPosX: 2,
//     spriteGridPosY: 12,
//     tileHeight: 2,
//     tileWidth: 1,
//     tileOffsetX: 0,
//     tileOffsetY: -32,
//     multiplier: 32,
//     visionBlocking: false,
//     obstacle: true,
//     obstacleObstructionX: 1,
//     obstacleObstructionY: 3,
//     centerTileName: "centerCliffFace",
//     topEndTileName: {
//       name: "cliffTopRight",
//       offset: -96
//     },
//     attachments: [{
//       tileName: "cliffRightCenter",
//       neighborPosition: 0,
//       xOffset: 0,
//       yOffset: -64
//     }]

//   }, {
//     id: "cliffTopLeft",
//     spriteSheet: tileA5_outside,
//     spriteGridPosX: 0,
//     spriteGridPosY: 11,
//     tileHeight: 1,
//     tileWidth: 1,
//     tileOffsetX: 0,
//     tileOffsetY: 0,
//     multiplier: 32,
//     visionBlocking: false,
//     obstacle: true,
//     obstacleSide: "left",
//     obstacleObstructionX: 1,
//     obstacleObstructionY: 1,
//   }, {
//     id: "cliffTopCenter",
//     spriteSheet: tileA5_outside,
//     spriteGridPosX: 1,
//     spriteGridPosY: 11,
//     tileHeight: 1,
//     tileWidth: 1,
//     tileOffsetX: 0,
//     tileOffsetY: 0,
//     multiplier: 32,
//     visionBlocking: false,
//     obstacle: true,
//     obstacleSide: "bottom",
//     obstacleObstructionX: 1,
//     obstacleObstructionY: 1,
//   }, {
//     id: "cliffTopRight",
//     spriteSheet: tileA5_outside,
//     spriteGridPosX: 2,
//     spriteGridPosY: 11,
//     tileHeight: 1,
//     tileWidth: 1,
//     tileOffsetX: 0,
//     tileOffsetY: 0,
//     multiplier: 32,
//     visionBlocking: false,
//     obstacle: true,
//     obstacleSide: "right",
//     obstacleObstructionX: 1,
//     obstacleObstructionY: 1,
//   }, {
//     id: "cliffLeftEdge",
//     spriteSheet: tileA5_outside,
//     spriteGridPosX: 0,
//     spriteGridPosY: 12,
//     tileHeight: 1,
//     tileWidth: 1,
//     tileOffsetX: 0,
//     tileOffsetY: 0,
//     multiplier: 32,
//     visionBlocking: false,
//     obstacle: true,
//     obstacleObstructionX: 1,
//     obstacleObstructionY: 1,
//   }, {
//     id: "cliffCenter",
//     spriteSheet: tileA5_outside,
//     spriteGridPosX: 1,
//     spriteGridPosY: 12,
//     tileHeight: 1,
//     tileWidth: 1,
//     tileOffsetX: 0,
//     tileOffsetY: 0,
//     multiplier: 32,
//     visionBlocking: false,
//     obstacle: true,
//     obstacleObstructionX: 1,
//     obstacleObstructionY: 1,
//   }, {
//     id: "cliffRightCenter",
//     spriteSheet: tileA5_outside,
//     spriteGridPosX: 2,
//     spriteGridPosY: 12,
//     tileHeight: 1,
//     tileWidth: 1,
//     tileOffsetX: 0,
//     tileOffsetY: 0,
//     multiplier: 32,
//     visionBlocking: false,
//     obstacle: true,
//     obstacleObstructionX: 1,
//     obstacleObstructionY: 1,
//   },
//   {
//     id: "leftCliffEdge",
//     spriteSheet: tileA5_outside,
//     spriteGridPosX: 0,
//     spriteGridPosY: 10,
//     tileHeight: 1,
//     tileWidth: 1,
//     tileOffsetX: 0,
//     tileOffsetY: 0,
//     multiplier: 32,
//     visionBlocking: false,
//     obstacle: false,
//     obstacleObstructionX: 1,
//     obstacleObstructionY: 1,
//   },
//   {
//     id: "rightCliffEdge",
//     spriteSheet: tileA5_outside,
//     spriteGridPosX: 0,
//     spriteGridPosY: 9,
//     tileHeight: 1,
//     tileWidth: 1,
//     tileOffsetX: 0,
//     tileOffsetY: 0,
//     multiplier: 32,
//     visionBlocking: false,
//     obstacle: false,
//     obstacleObstructionX: 1,
//     obstacleObstructionY: 1,
//   },
//   {
//     id: "leftCliffBottomEdge",
//     spriteSheet: tileA5_outside,
//     spriteGridPosX: 0,
//     spriteGridPosY: 13,
//     tileHeight: 1,
//     tileWidth: 1,
//     tileOffsetX: 0,
//     tileOffsetY: 0,
//     multiplier: 32,
//     visionBlocking: false,
//     obstacle: true,
//     obstacleObstructionX: 1,
//     obstacleObstructionY: 1,
//   },
//   {
//     id: "CenterCliffBottomEdge",
//     spriteSheet: tileA5_outside,
//     spriteGridPosX: 1,
//     spriteGridPosY: 13,
//     tileHeight: 1,
//     tileWidth: 1,
//     tileOffsetX: 0,
//     tileOffsetY: 0,
//     multiplier: 32,
//     visionBlocking: false,
//     obstacle: true,
//     obstacleObstructionX: 1,
//     obstacleObstructionY: 1,
//   },
//   {
//     id: "rightCliffBottomEdge",
//     spriteSheet: tileA5_outside,
//     spriteGridPosX: 2,
//     spriteGridPosY: 13,
//     tileHeight: 1,
//     tileWidth: 1,
//     tileOffsetX: 0,
//     tileOffsetY: 0,
//     multiplier: 32,
//     visionBlocking: false,
//     obstacle: true,
//     obstacleObstructionX: 1,
//     obstacleObstructionY: 1,
//   },

// ]