export const tileB_outside = new Image()
tileB_outside.src = "assets/images/tileB_outside.png"
export const tileA5_outside = new Image()
tileA5_outside.src = "assets/images/tileA5_outside.png"
export const tileA2_outside = new Image()
tileA2_outside.src = "assets/images/tileA2_outside.png"
export const greenGrassEdges = new Image()
greenGrassEdges.src = "assets/images/greenGrassEdges.png"
export const tf_winter_tileB = new Image()
tf_winter_tileB.src = "assets/images/tf_winter_tileB.png"
export const tileB_desert = new Image()
tileB_desert.src = "assets/images/tileB_desert.png"
export const tileA5_dungeon = new Image()
tileA5_dungeon.src = "assets/images/tileA5_dungeon1.png"
export const tileB_dungeon = new Image()
tileB_dungeon.src = "assets/images/tileB_dungeon.png"
export const dungeon_extension = new Image()
dungeon_extension.src = "assets/images/dungeon_extension.png"