import { GrowablePanelPosition, SpriteTile } from "../../models/cell.model";
import { tf_winter_tileB, tileB_desert, tileB_outside } from "./images";

export const trees: SpriteTile[] = [
  {
    id: "treeClumpTopLeft",
    spriteSheet: tileB_outside,
    spriteGridPosX: 0,
    spriteGridPosY: 10,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: false,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: true,
      bottomLeftNeighbor: null,
      leftNeighbor: false,
      topLeftNeighbor: false,
    }
  },
  {
    id: "treeClumpTopCenter",
    spriteSheet: tileB_outside,
    spriteGridPosX: 1,
    spriteGridPosY: 10,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: false,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  }, {
    id: "treeClumpTopRight",
    spriteSheet: tileB_outside,
    spriteGridPosX: 2,
    spriteGridPosY: 10,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: false,
      topRightNeighbor: false,
      rightNeighbor: false,
      bottomRightNeighbor: null,
      bottomNeighbor: true,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  },
  {
    id: "treeClumpGrowableLeft",
    spriteSheet: tileB_outside,
    spriteGridPosX: 0,
    spriteGridPosY: 11,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: true,
      bottomLeftNeighbor: null,
      leftNeighbor: false,
      topLeftNeighbor: false, // this one
    }
  }, {
    id: "treeClumpGrowableCenter",
    spriteSheet: tileB_outside,
    spriteGridPosX: 1,
    spriteGridPosY: 11,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: true,
    }

  }, {
    id: "treeClumpGrowableRight",
    spriteSheet: tileB_outside,
    spriteGridPosX: 2,
    spriteGridPosY: 11,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: false,
      rightNeighbor: false,
      bottomRightNeighbor: null,
      bottomNeighbor: true,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  }, {
    id: "treeClumpTrunkLeft",
    spriteSheet: tileB_outside,
    spriteGridPosX: 2,
    spriteGridPosY: 13,
    tileHeight: 3,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: false,
      bottomLeftNeighbor: false,
      leftNeighbor: false,
      topLeftNeighbor: false,
    }
  },
  {
    id: "treeClumpTrunkCenter",
    default: true,
    spriteSheet: tileB_outside,
    spriteGridPosX: 3,
    spriteGridPosY: 13,
    tileHeight: 3,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: false,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  },
  {
    id: "treeClumpTrunkRight",
    spriteSheet: tileB_outside,
    spriteGridPosX: 4,
    spriteGridPosY: 13,
    tileHeight: 3,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: false,
      rightNeighbor: false,
      bottomRightNeighbor: false,
      bottomNeighbor: false,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  },
  {
    id: "treeClumpTrunkLeftAngle",
    spriteSheet: tileB_outside,
    spriteGridPosX: 1,
    spriteGridPosY: 13,
    tileHeight: 3,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: false,
      bottomLeftNeighbor: false,
      leftNeighbor: false,
      topLeftNeighbor: true,
    }
  },
  {
    id: "treeClumpTrunkRightAngle",
    spriteSheet: tileB_outside,
    spriteGridPosX: 5,
    spriteGridPosY: 13,
    tileHeight: 3,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: true,
      rightNeighbor: false,
      bottomRightNeighbor: false,
      bottomNeighbor: false,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  },
  {
    id: "treeClumpLeftFillerAngle",
    spriteSheet: tileB_outside,
    spriteGridPosX: 6,
    spriteGridPosY: 10,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: false,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: true,

    }
  },
  {
    id: "treeClumpRightFillerAngle",
    spriteSheet: tileB_outside,
    spriteGridPosX: 7,
    spriteGridPosY: 10,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {

      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: false,
      leftNeighbor: true,
      topLeftNeighbor: true,
    }
  },
  {
    id: "treeClumpLeftFillerAngleUP",
    spriteSheet: tileB_outside,
    spriteGridPosX: 6,
    spriteGridPosY: 11,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: false,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: true,

    }
  },
  {
    id: "treeClumpRightFillerAngleUp",
    spriteSheet: tileB_outside,
    spriteGridPosX: 7,
    spriteGridPosY: 11,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {

      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: false,
    }
  },
  {
    id: "treeClumpRightAngleGapFiller",
    spriteSheet: tileB_outside,
    spriteGridPosX: 6,
    spriteGridPosY: 14,
    tileHeight: 2, 
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: false,
      bottomRightNeighbor: false,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: true,
    } 
  },
  {
    id: "treeClumpLeftAngleGapFiller",
    spriteSheet: tileB_outside,
    spriteGridPosX: 7,
    spriteGridPosY: 14,
    tileHeight: 2, 
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: false,
      leftNeighbor: false,
      topLeftNeighbor: true,
    } 
  },
  {
    id: "treeClumpLeftFillerAngleSingle",
    spriteSheet: tileB_outside,
    spriteGridPosX: 7,
    spriteGridPosY: 14,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: false,
      topLeftNeighbor: true,
    } 
  },
  {
    id: "treeClumpRightFillerAngleSingle",
    spriteSheet: tileB_outside,
    spriteGridPosX: 6,
    spriteGridPosY: 14,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: 0,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: false,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: true,
    } 
  },
]

export const trees2: SpriteTile[] = [
  {
    id: "tree1",
    spriteSheet: tileB_outside,
    spriteGridPosX: 8,
    spriteGridPosY: 4,
    tileHeight: 6,
    tileWidth: 6,
    tileOffsetX: -80,
    tileOffsetY: -160,
    multiplier: 32,
    visionBlocking: true,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  }, {
    id: "tree2",
    spriteSheet: tileB_outside,
    spriteGridPosX: 8,
    spriteGridPosY: 0,
    tileHeight: 4,
    tileWidth: 4,
    tileOffsetX: -48,
    tileOffsetY: -96,
    multiplier: 32,
    obstacle: true,
    visionBlocking: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  }, {
    id: "treeStumpsForrest1",
    spriteSheet: tileB_outside,
    spriteGridPosX: 14,
    spriteGridPosY: 4,
    tileHeight: 2,
    tileWidth: 2,
    tileOffsetX: 0,
    tileOffsetY: -32,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 2,
    obstacleObstructionY: 2,
    allowForPassThrough: true
  }, {
    id: "treeStumpsForrest2",
    spriteSheet: tileB_outside,
    spriteGridPosX: 14,
    spriteGridPosY: 6,
    tileHeight: 2,
    tileWidth: 2,
    tileOffsetX: 0,
    tileOffsetY: -32,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 2,
    obstacleObstructionY: 2,
    allowForPassThrough: true
  }, {
    id: "treeStumpsForrest36",
    spriteSheet: tileB_outside,
    spriteGridPosX: 14,
    spriteGridPosY: 8,
    tileHeight: 2,
    tileWidth: 2,
    tileOffsetX: 0,
    tileOffsetY: -32,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 2,
    obstacleObstructionY: 2,
    allowForPassThrough: true
  }, {
    id: "treeLog",
    spriteSheet: tileB_outside,
    spriteGridPosX: 5,
    spriteGridPosY: 8,
    tileHeight: 2,
    tileWidth: 3,
    tileOffsetX: -0,
    tileOffsetY: -16,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  }, {
    id: "grassCross",
    spriteSheet: tileB_outside,
    spriteGridPosX: 6,
    spriteGridPosY: 5,
    tileHeight: 2,
    tileWidth: 1,
    tileOffsetX: -0,
    tileOffsetY: -32,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  }, {
    id: "grassGraveStone",
    spriteSheet: tileB_outside,
    spriteGridPosX: 5,
    spriteGridPosY: 5,
    tileHeight: 2,
    tileWidth: 1,
    tileOffsetX: -0,
    tileOffsetY: -32,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  }, {
    id: "grassGraveStone",
    spriteSheet: tileB_outside,
    spriteGridPosX: 4,
    spriteGridPosY: 5,
    tileHeight: 2,
    tileWidth: 1,
    tileOffsetX: -0,
    tileOffsetY: -32,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  }, {
    id: "smallWoodPile1",
    spriteSheet: tileB_outside,
    spriteGridPosX: 7,
    spriteGridPosY: 6,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: -0,
    tileOffsetY: -0,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  }, {
    id: "smallWoodPile2",
    spriteSheet: tileB_outside,
    spriteGridPosX: 7,
    spriteGridPosY: 7,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: -0,
    tileOffsetY: -0,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  }, {
    id: "smallRockPile1",
    spriteSheet: tileB_outside,
    spriteGridPosX: 7,
    spriteGridPosY: 4,
    tileHeight: 2,
    tileWidth: 1,
    tileOffsetX: -0,
    tileOffsetY: -32,
    multiplier: 32,
    visionBlocking: false,
    obstacle: true,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
  },
  {
    id: "pineTree",
    spriteSheet: tf_winter_tileB,
    spriteGridPosX: 0,
    spriteGridPosY: 6,
    tileHeight: 4,
    tileWidth: 3,
    tileOffsetX: -32,
    tileOffsetY: -96,
    multiplier: 32,
    visionBlocking: true,
    obstacle: true,
    obstacleObstructionX: 2,
    obstacleObstructionY: 2,
  },
  {
    id: "cypressTree",
    spriteSheet: tf_winter_tileB,
    spriteGridPosX: 0,
    spriteGridPosY: 10,
    tileHeight: 3,
    tileWidth: 3,
    tileOffsetX: -32,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: true,
    obstacle: true,
    obstacleObstructionX: 2,
    obstacleObstructionY: 2,
  },
  {
    id: "DeadTree",
    spriteSheet: tf_winter_tileB,
    spriteGridPosX: 8,
    spriteGridPosY: 0,
    tileHeight: 3,
    tileWidth: 3,
    tileOffsetX: -32,
    tileOffsetY: -64,
    multiplier: 32,
    visionBlocking: true,
    obstacle: true,
    obstacleObstructionX: 2,
    obstacleObstructionY: 2,
  },
  {
    id: "DeadTree1",
    spriteSheet: tileB_desert,
    spriteGridPosX: 0,
    spriteGridPosY: 6,
    tileHeight: 4,
    tileWidth: 2,
    tileOffsetX: -16,
    tileOffsetY: -96,
    multiplier: 32,
    visionBlocking: true,
    obstacle: true,
    obstacleObstructionX: 2,
    obstacleObstructionY: 2,
  },
  {
    id: "DeadTree2",
    spriteSheet: tileB_desert,
    spriteGridPosX: 4,
    spriteGridPosY: 6,
    tileHeight: 4,
    tileWidth: 3,
    tileOffsetX: -16,
    tileOffsetY: -96,
    multiplier: 32,
    visionBlocking: true,
    obstacle: true,
    obstacleObstructionX: 2,
    obstacleObstructionY: 2,
  },
]



